import React from 'react';
import styled from 'styled-components/macro';
import { Feature } from '../Feature';
import imgPlaceholder from '../../../../../assets/placeholder.svg';
import imgMtFeature from '../../../../../assets/mt-feature.svg';
import { StakeVote } from './StakeVote';

export function Features() {
  return (
    <>
      <div className="w-100 text-center">
        <How>Sovryn protocol features</How>
      </div>

      <Feature
        title="Liquidity Mining"
        content={
          <>
            Sovryn waves goodbye to centralised services that conventionally
            provide market-making. Fees generated by trading are distributed
            amongst liquidity providers as a reward, in exchange for
            facilitating trades and swaps.{' '}
            <a
              href="https://wiki.sovryn.app/en/technical-documents/amm/AMM-FAQ"
              target="_blank"
              rel="noreferrer noopener"
            >
              Learn more
            </a>
          </>
        }
        image={imgPlaceholder}
        cta="Mine"
        href="/liquidity"
        reverse
      />

      <Feature
        title="Margin Trading"
        content={
          <>
            Margin trading allows you to use assets in your wallet as collateral
            for your margin, to borrow more assets or to increase your initial
            position.{' '}
            <a
              href="https://wiki.sovryn.app/en/sovryn-dapp/trading#margin-trading-on-sovryn"
              target="_blank"
              rel="noreferrer noopener"
            >
              Learn more
            </a>
          </>
        }
        image={imgMtFeature}
        cta="Trade"
        href="/trade"
      />

      <Feature
        title="Swap"
        content={
          <>
            Swap Frictionlessly between listed tokens. The Sovryn Decentralized
            AMM ensures no one can take advantage of you creating a trade.{' '}
            <a
              href="https://wiki.sovryn.app/en/sovryn-dapp/trading#step-1-go-to-the-sovryn-dapp"
              target="_blank"
              rel="noreferrer noopener"
            >
              Learn more
            </a>
          </>
        }
        image={imgPlaceholder}
        cta="Swap"
        href="/trade?swap"
        reverse
      />

      <Feature
        title="Market Making"
        content={
          <>
            Sovryn’s layer 2 solution operating on the Rootstock (RSK) Bitcoin
            side-chain facilitates the frictionless usage of financial
            primitives for multiple assets across multiple chains to further
            Satoshi’s vision of monetary sovereignty beyond simple peer to peer
            transactions.
            <a
              href="https://wiki.sovryn.app/en/sovryn-dapp/market-making#video-how-to-earn-by-market-making"
              target="_blank"
              rel="noreferrer noopener"
            >
              Learn more
            </a>
          </>
        }
        image={imgPlaceholder}
        cta="Market Maker"
        href="/liquidity"
      />

      <Feature
        title="Lending"
        content={
          <>
            Earn a passive income by lending your assets directly to borrowers
            or to margin traders and decrease your exposure to wider market
            performances and fluctuations. Sovryn’s non-custodial solution keeps
            you in control of your funds, and you are free to withdraw your
            assets at any time.{' '}
            <a
              href="https://wiki.sovryn.app/en/sovryn-dapp/lending"
              target="_blank"
              rel="noreferrer noopener"
            >
              Learn more
            </a>
          </>
        }
        image={imgPlaceholder}
        cta="Trade"
        href="/loans"
        reverse
      />
      <StakeVote />
    </>
  );
}

const How = styled.h1`
  font-size: 36px;
  letter-spacing: 4.3px;
  line-height: 47px;
  text-transform: none;
`;
