export enum Asset {
  CSOV = 'CSOV',
  RBTC = 'RBTC',
  WRBTC = 'WRBTC',
  /** Sovryn BSC Network BTC wrapper for Perpetuals */
  BTCS = 'BTCS',
  ETH = 'ETH',
  DOC = 'DOC',
  RDOC = 'RDOC',
  USDT = 'USDT',
  XUSD = 'XUSD',
  XUSD_legacy = 'XUSD_legacy',
  BPRO = 'BPRO',
  SOV = 'SOV',
  MOC = 'MOC',
  BNB = 'BNBS',
  BNBS = 'BNBS',
  FISH = 'FISH',
  TRADING = 'TRADING',
  RIF = 'RIF',
  MYNT = 'MYNT',
  ZUSD = 'ZUSD',
}
