export enum ChainId {
  ETH_MAINNET = 1,
  ETH_TESTNET = 3, // Ropsten
  ETH_RINKEBY = 4,
  RSK_MAINNET = 30,
  RSK_TESTNET = 31,
  BSC_MAINNET = 56,
  BSC_TESTNET = 97,
  MATIC_MAINNET = 137, // Polygon
  MATIC_TESTNET = 80001,
}
