export enum CrossBridgeAsset {
  RBTC = 'RBTC',
  ETH = 'ETH',
  ETHS = 'ETHS',
  BNB = 'BNB',
  BNBS = 'BNBS',
  SOV = 'SOV',
  ESOV = 'ESOV',
  BSOV = 'BSOV',
  XUSD = 'XUSD',
  USDT = 'USDT',
  USDC = 'USDC',
  BUSD = 'BUSD',
  DAI = 'DAI',
  RUSDT = 'RUSDT',
  DLLR = 'DLLR',
  EDLLR = 'EDLLR',
}
