import { PerpetualManager } from 'abiTypes/PerpetualManager';
import { Asset } from 'types/asset';
import { AssetsDictionary } from '../dictionaries/assets-dictionary';
import { Sovryn } from '../sovryn';
import { ContractName } from '../types/contracts';
import { appContracts } from './app-contracts';

export const getLendingContract = (asset: Asset) =>
  AssetsDictionary.get(asset).lendingContract;

export const getLendingContractName = (asset: Asset) =>
  AssetsDictionary.get(asset).getLendingContractName();

export const getTokenContract = (asset: Asset) =>
  AssetsDictionary.get(asset).tokenContract;

export const getTokenLendingContract = (asset: Asset) =>
  AssetsDictionary.get(asset).lendingContract;

export const getTokenContractName = (asset: Asset) =>
  AssetsDictionary.get(asset).getTokenContractName();

export const getWeb3Contract = (address: string, abi: any) => {
  const web3 = Sovryn.getWeb3();
  return new web3.eth.Contract(abi, address);
};

// This function will accept a contract name and a function name as parameters. It could either accept an interface generated by Typechain as a parameter as well or we will
// have some switch that will return the proper interface based on the contract passed (probably the second option would be the most user friendly).
export const getFunctionSignature = () => {
  const contract = getContract('perpetualManager');
  const web3 = Sovryn.getWeb3();
  const perpetualManager = (new web3.eth.Contract(
    contract.abi,
    contract.address,
  ) as any) as PerpetualManager;

  return perpetualManager.methods.createPerpetual;
};

export const getContract = (contractName: ContractName) =>
  appContracts[contractName];

export const getContractNameByAddress = (address: string): ContractName => {
  return Object.keys(Sovryn.contracts).find(
    key =>
      Sovryn.contracts[key].options.address.toLowerCase() ===
      address.toLowerCase(),
  ) as ContractName;
};

export const symbolByTokenAddress = (address: string) => {
  return AssetsDictionary.getByTokenContractAddress(address)?.symbol;
};

export const assetByTokenAddress = (address: string): Asset => {
  return AssetsDictionary.getByTokenContractAddress(address)?.asset;
};

export const assetByLoanTokenAddress = (address: string): Asset => {
  return AssetsDictionary.getByLoanContractAddress(address)?.asset;
};
