# Syncs "master" branch to "master_external"

name: 'Sync Master External'
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: lts/erbium
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'master'
          TO_BRANCH: 'master_external'
          PULL_REQUEST_BODY: 'sync-branches: Syncing commits from `master` to `master_external`'
